services:
  - type: web
    name: rainboweasywalk
    env: java
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/rainboweasywalk-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: DB_URL
        value: jdbc:postgresql://turntable.proxy.rlwy.net:54530/railway
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: SfRPGDXDSAdWwXaPUEuIrYfsRshzpfna
      - key: FRONTEND_URL
        value: http://localhost:3000
